#!/bin/bash

# Usage: xmlcols histogram_name col1 col2... < hist.xml > out.dat
#
# Usage examples:
#  xmlcols h1 binNum	entries	height	error < hist.xml > out.dat
#  xmlcols hh1 binNumX	binNumY	entries	height	error < hist.xml > out.dat
#
# Note: columns must be given in the same order as they appear in the file.

NAME="$1"
COLUMNS="${*:2}"

#COLUMNS='binNumX	binNumY	entries	height	error'
#COLUMNS='binNum	entries	height	error'

RANGE="/<histogram[12]d[^<>]\+name=\"$NAME\"/,/<\/histogram/"
RE='[ \t]*<bin[12]d'
SUB=''
CNT=0

for col in $COLUMNS; do
	let ++CNT
	RE+="[^<>]*[ \t]$col=\"\([-+0-9.eE]\+\)\""
	if [ $CNT -ne 1 ]; then
		SUB+='	'
	fi
	SUB+="\\$CNT"
done

RE+=".*"

echo "#$COLUMNS"
sed -ne "$RANGE s/$RE/$SUB/p"
